version: '3.8'

services:
  homeutilities:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release # Or Debug if you prefer
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Or Production
    # If you need to link to other services, define them below
    # links:
    #   - database
    # depends_on:
    #   - database
    # volumes:
    #   - ./data:/app/data